FROM mhart/alpine-node:10

RUN apk update && apk add bash && rm -rf /var/cache/apk/*

RUN mkdir -p /usr/src/app
ADD . /usr/src/app

WORKDIR /usr/src/app

RUN npm i
RUN mkdir ./dist
RUN npm run build

CMD npm run serve
